version: '3.8'

services:
  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - inner-network

  backend:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - redis
    networks:
      - inner-network

volumes:
  redis-data:

networks:
  inner-network:
    driver: bridge